name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ${{ github.token }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker build . -t ghcr.io/${{ github.repository}}:$GITHUB_REF_NAME
        docker push ghcr.io/${{ github.repository}}:$GITHUB_REF_NAME
